// benchmarks/todomvc-react/App.jsx
import { useState, useEffect, useCallback } from "react";
import { flushSync } from "react-dom";

const STORAGE_KEY = "todomvc-react";

function loadTodos() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch {
    return [];
  }
}

function saveTodos(todos) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(todos));
}

let nextId = 1;

export default function App() {
  const [todos, setTodos] = useState(() => {
    const loaded = loadTodos();
    if (loaded.length) {
      nextId = Math.max(...loaded.map((t) => t.id)) + 1;
    }
    return loaded;
  });
  const [newText, setNewText] = useState("");
  const [filter, setFilter] = useState("all");

  useEffect(() => {
    saveTodos(todos);
  }, [todos]);

  // Benchmark API — expose state manipulation on window
  useEffect(() => {
    const adj = ["pretty","large","big","small","tall","short","long","handsome","plain","quaint","clean","elegant","easy","angry","crazy","helpful","mushy","odd","unsightly","adorable","important","inexpensive","cheap","expensive","fancy"];
    const col = ["red","yellow","blue","green","pink","brown","purple","brown","white","black","orange"];
    const noun = ["table","chair","house","bbq","desk","car","pony","cookie","sandwich","burger","pizza","mouse","keyboard"];
    function buildTitle(i) { return `${adj[i % adj.length]} ${col[i % col.length]} ${noun[i % noun.length]}`; }

    window.__benchFlush = () => Promise.resolve(); // flushSync is already synchronous
    window.__bench = {
      createRows(n) {
        flushSync(() => setTodos(prev => {
          const newTodos = [];
          for (let i = 0; i < n; i++) newTodos.push({ id: nextId++, title: buildTitle(i), completed: false });
          return [...prev, ...newTodos];
        }));
      },
      clearRows() { flushSync(() => setTodos([])); },
      updateEvery10th() { flushSync(() => setTodos(prev => prev.map((t, i) => i % 10 === 0 ? { ...t, title: t.title + " !!!" } : t))); },
      deleteEvery10th() { flushSync(() => setTodos(prev => prev.filter((_, i) => i % 10 !== 0))); },
      swapRows(a, b) {
        flushSync(() => setTodos(prev => {
          if (!prev[a] || !prev[b]) return prev;
          const next = [...prev]; const tmp = next[a]; next[a] = next[b]; next[b] = tmp; return next;
        }));
      },
      removeRow(idx) { flushSync(() => setTodos(prev => idx >= 0 && idx < prev.length ? prev.filter((_, i) => i !== idx) : prev)); },
      selectRow() { flushSync(() => setFilter(f => f)); },
      reset() { flushSync(() => { setTodos([]); nextId = 1; }); },
    };
  }, []);

  function addTodo(e) {
    e.preventDefault();
    const text = newText.trim();
    if (!text) return;
    setTodos((prev) => [...prev, { id: nextId++, title: text, completed: false }]);
    setNewText("");
  }

  function toggleTodo(id) {
    setTodos((prev) =>
      prev.map((t) => (t.id === id ? { ...t, completed: !t.completed } : t))
    );
  }

  function toggleAll() {
    const allDone = todos.every((t) => t.completed);
    setTodos((prev) => prev.map((t) => ({ ...t, completed: !allDone })));
  }

  function deleteTodo(id) {
    setTodos((prev) => prev.filter((t) => t.id !== id));
  }

  function clearCompleted() {
    setTodos((prev) => prev.filter((t) => !t.completed));
  }

  const activeCount = todos.filter((t) => !t.completed).length;
  const completedCount = todos.filter((t) => t.completed).length;

  const visibleTodos =
    filter === "active"
      ? todos.filter((t) => !t.completed)
      : filter === "completed"
        ? todos.filter((t) => t.completed)
        : todos;

  return (
    <div className="todoapp">
      <header className="header">
        <h1>todos</h1>
        <form onSubmit={addTodo}>
          <input
            className="new-todo"
            type="text"
            placeholder="What needs to be done?"
            value={newText}
            onChange={(e) => setNewText(e.target.value)}
            autoFocus
          />
        </form>
      </header>

      {todos.length > 0 && (
        <section className="main">
          <input
            id="toggle-all"
            className="toggle-all"
            type="checkbox"
            checked={activeCount === 0}
            onChange={toggleAll}
          />
          <label htmlFor="toggle-all">Mark all as complete</label>
          <ul className="todo-list">
            {visibleTodos.map((todo) => (
              <li key={todo.id} className="todo-item">
                <div className="view">
                  <input
                    className="toggle"
                    type="checkbox"
                    checked={todo.completed}
                    onChange={() => toggleTodo(todo.id)}
                  />
                  <label>{todo.title}</label>
                  <button className="destroy" onClick={() => deleteTodo(todo.id)} />
                </div>
              </li>
            ))}
          </ul>
        </section>
      )}

      {todos.length > 0 && (
        <footer className="footer">
          <span className="todo-count">
            <strong>{activeCount}</strong>
            {activeCount === 1 ? " item left" : " items left"}
          </span>
          <ul className="filters">
            <li>
              <a
                href="#/"
                className={filter === "all" ? "selected" : ""}
                onClick={() => setFilter("all")}
              >
                All
              </a>
            </li>
            <li>
              <a
                href="#/active"
                className={filter === "active" ? "selected" : ""}
                onClick={() => setFilter("active")}
              >
                Active
              </a>
            </li>
            <li>
              <a
                href="#/completed"
                className={filter === "completed" ? "selected" : ""}
                onClick={() => setFilter("completed")}
              >
                Completed
              </a>
            </li>
          </ul>
          {completedCount > 0 && (
            <button className="clear-completed" onClick={clearCompleted}>
              Clear completed
            </button>
          )}
        </footer>
      )}
    </div>
  );
}

// benchmarks/todomvc-svelte/src/App.svelte
<script>
  import { tick } from "svelte";
  const STORAGE_KEY = "todomvc-svelte5";

  function loadTodos() {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  }

  function saveTodos(todos) {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(todos));
  }

  let todos = $state(loadTodos());
  let newTodoText = $state("");
  let filter = $state("all");
  let nextId = $state(
    todos.length ? Math.max(...todos.map((t) => t.id)) + 1 : 1
  );

  let activeCount = $derived(todos.filter((t) => !t.completed).length);
  let completedCount = $derived(todos.filter((t) => t.completed).length);
  let allDone = $derived(todos.length > 0 && activeCount === 0);
  let visibleTodos = $derived(
    filter === "active"
      ? todos.filter((t) => !t.completed)
      : filter === "completed"
        ? todos.filter((t) => t.completed)
        : todos
  );

  function addTodo(e) {
    e.preventDefault();
    const text = newTodoText.trim();
    if (!text) return;
    todos = [...todos, { id: nextId, title: text, completed: false }];
    nextId++;
    newTodoText = "";
    saveTodos(todos);
  }

  function toggleTodo(id) {
    todos = todos.map((t) =>
      t.id === id ? { ...t, completed: !t.completed } : t
    );
    saveTodos(todos);
  }

  function toggleAll() {
    const target = !allDone;
    todos = todos.map((t) => ({ ...t, completed: target }));
    saveTodos(todos);
  }

  function deleteTodo(id) {
    todos = todos.filter((t) => t.id !== id);
    saveTodos(todos);
  }

  function clearCompleted() {
    todos = todos.filter((t) => !t.completed);
    saveTodos(todos);
  }

  // Benchmark API
  window.__benchFlush = () => tick();
  const adj = ["pretty","large","big","small","tall","short","long","handsome","plain","quaint","clean","elegant","easy","angry","crazy","helpful","mushy","odd","unsightly","adorable","important","inexpensive","cheap","expensive","fancy"];
  const col = ["red","yellow","blue","green","pink","brown","purple","brown","white","black","orange"];
  const noun = ["table","chair","house","bbq","desk","car","pony","cookie","sandwich","burger","pizza","mouse","keyboard"];
  function buildTitle(i) { return `${adj[i % adj.length]} ${col[i % col.length]} ${noun[i % noun.length]}`; }

  window.__bench = {
    createRows(n) {
      const newTodos = [];
      for (let i = 0; i < n; i++) newTodos.push({ id: nextId++, title: buildTitle(i), completed: false });
      todos = [...todos, ...newTodos];
    },
    clearRows() { todos = []; },
    updateEvery10th() { todos = todos.map((t, i) => i % 10 === 0 ? { ...t, title: t.title + " !!!" } : t); },
    deleteEvery10th() { todos = todos.filter((_, i) => i % 10 !== 0); },
    swapRows(a, b) {
      if (todos[a] && todos[b]) {
        const next = [...todos]; const tmp = next[a]; next[a] = next[b]; next[b] = tmp; todos = next;
      }
    },
    removeRow(idx) { if (idx >= 0 && idx < todos.length) todos = todos.filter((_, i) => i !== idx); },
    selectRow() { filter = filter; },
    reset() { todos = []; nextId = 1; },
  };
</script>

<div class="todoapp">
  <header class="header">
    <h1>todos</h1>
    <form onsubmit={addTodo}>
      <input
        class="new-todo"
        type="text"
        placeholder="What needs to be done?"
        bind:value={newTodoText}
        autofocus
      />
    </form>
  </header>

  {#if todos.length}
    <section class="main">
      <input
        id="toggle-all"
        class="toggle-all"
        type="checkbox"
        checked={allDone}
        onchange={toggleAll}
      />
      <label for="toggle-all">Mark all as complete</label>
      <ul class="todo-list">
        {#each visibleTodos as todo (todo.id)}
          <li class="todo-item">
            <div class="view">
              <input
                class="toggle"
                type="checkbox"
                checked={todo.completed}
                onchange={() => toggleTodo(todo.id)}
              />
              <label>{todo.title}</label>
              <button class="destroy" onclick={() => deleteTodo(todo.id)}
              ></button>
            </div>
          </li>
        {/each}
      </ul>
    </section>

    <footer class="footer">
      <span class="todo-count">
        <strong>{activeCount}</strong>
        {activeCount === 1 ? " item left" : " items left"}
      </span>
      <ul class="filters">
        <li>
          <a
            href="#/"
            class:selected={filter === "all"}
            onclick={() => (filter = "all")}>All</a
          >
        </li>
        <li>
          <a
            href="#/active"
            class:selected={filter === "active"}
            onclick={() => (filter = "active")}>Active</a
          >
        </li>
        <li>
          <a
            href="#/completed"
            class:selected={filter === "completed"}
            onclick={() => (filter = "completed")}>Completed</a
          >
        </li>
      </ul>
      {#if completedCount > 0}
        <button class="clear-completed" onclick={clearCompleted}
          >Clear completed</button
        >
      {/if}
    </footer>
  {/if}
</div>

<style>
  :global(body) {
    font: 14px "Helvetica Neue", Helvetica, Arial, sans-serif;
    line-height: 1.4em;
    background: #f5f5f5;
    color: #111111;
    min-width: 230px;
    max-width: 550px;
    margin: 0 auto;
    font-weight: 300;
  }

  .todoapp {
    background: #fff;
    margin: 130px 0 40px 0;
    position: relative;
    box-shadow:
      0 2px 4px 0 rgba(0, 0, 0, 0.2),
      0 25px 50px 0 rgba(0, 0, 0, 0.1);
  }

  .todoapp h1 {
    position: absolute;
    top: -140px;
    width: 100%;
    font-size: 80px;
    font-weight: 200;
    text-align: center;
    color: #b83f45;
    text-rendering: optimizeLegibility;
  }

  .new-todo {
    padding: 16px 16px 16px 60px;
    height: 65px;
    border: none;
    background: rgba(0, 0, 0, 0.003);
    box-shadow: inset 0 -2px 1px rgba(0, 0, 0, 0.03);
    position: relative;
    margin: 0;
    width: 100%;
    font-size: 24px;
    font-family: inherit;
    font-weight: inherit;
    line-height: 1.4em;
    color: inherit;
    box-sizing: border-box;
  }

  .new-todo::placeholder {
    font-style: italic;
    font-weight: 400;
    color: rgba(0, 0, 0, 0.4);
  }

  .main {
    position: relative;
    z-index: 2;
    border-top: 1px solid #e6e6e6;
  }

  .toggle-all {
    width: 1px;
    height: 1px;
    border: none;
    opacity: 0;
    position: absolute;
    right: 100%;
    bottom: 100%;
  }

  .toggle-all + label {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 45px;
    height: 65px;
    font-size: 0;
    position: absolute;
    top: -65px;
    left: -0px;
  }

  .toggle-all + label:before {
    content: "\276F";
    display: inline-block;
    font-size: 22px;
    color: #949494;
    padding: 10px 27px 10px 27px;
    transform: rotate(90deg);
  }

  .todo-list {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  .todo-item {
    position: relative;
    font-size: 24px;
    border-bottom: 1px solid #ededed;
  }

  .todo-item .view {
    display: flex;
    align-items: center;
  }

  .todo-item .toggle {
    text-align: center;
    width: 40px;
    height: 40px;
    margin: auto 0;
    border: none;
    appearance: none;
    cursor: pointer;
  }

  .todo-item label {
    word-break: break-all;
    padding: 15px 15px 15px 15px;
    display: block;
    line-height: 1.2;
    transition: color 0.4s;
    font-weight: 400;
    color: #484848;
    flex: 1;
  }

  .todo-item .destroy {
    display: none;
    position: absolute;
    top: 0;
    right: 10px;
    bottom: 0;
    width: 40px;
    height: 40px;
    margin: auto 0;
    font-size: 30px;
    color: #949494;
    transition: color 0.2s ease-out;
    cursor: pointer;
    border: none;
    background: none;
  }

  .todo-item .destroy:after {
    content: "\00D7";
  }

  .todo-item:hover .destroy {
    display: block;
  }

  .todo-item .destroy:hover {
    color: #c18585;
  }

  .todo-item .edit {
    display: none;
  }

  .footer {
    padding: 10px 15px;
    height: 20px;
    text-align: center;
    font-size: 15px;
    border-top: 1px solid #e6e6e6;
  }

  .footer:before {
    content: "";
    position: absolute;
    right: 0;
    bottom: 0;
    left: 0;
    height: 50px;
    overflow: hidden;
    box-shadow:
      0 1px 1px rgba(0, 0, 0, 0.2),
      0 8px 0 -3px #f6f6f6,
      0 9px 1px -3px rgba(0, 0, 0, 0.2),
      0 16px 0 -6px #f6f6f6,
      0 17px 2px -6px rgba(0, 0, 0, 0.2);
  }

  .todo-count {
    float: left;
    text-align: left;
  }

  .filters {
    margin: 0;
    padding: 0;
    list-style: none;
    position: absolute;
    right: 0;
    left: 0;
  }

  .filters li {
    display: inline;
  }

  .filters li a {
    color: inherit;
    margin: 3px;
    padding: 3px 7px;
    text-decoration: none;
    border: 1px solid transparent;
    border-radius: 3px;
  }

  .filters li a:hover {
    border-color: #db7676;
  }

  :global(.filters li a.selected) {
    border-color: #ce4646;
  }

  .clear-completed {
    float: right;
    position: relative;
    line-height: 19px;
    text-decoration: none;
    cursor: pointer;
    border: none;
    background: none;
  }

  .clear-completed:hover {
    text-decoration: underline;
  }
</style>
